import { useState } from "react";
import { EMPTY_PRODUCT_FORM } from "../constants/product";
import { createSlug } from "../utils/slug";

export default function useProductForm() {
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [saving, setSaving] = useState(false);
  const [formData, setFormData] = useState({ ...EMPTY_PRODUCT_FORM });
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState("");
  const [galleryFiles, setGalleryFiles] = useState([]);
  const [galleryPreviews, setGalleryPreviews] = useState([]);
  const [existingGallery, setExistingGallery] = useState([]);
  const [deletedGalleryIds, setDeletedGalleryIds] = useState([]);

  function resetProductForm() {
    setEditingId(null);
    setFormData({ ...EMPTY_PRODUCT_FORM });
    setImageFile(null);
    setImagePreview("");
    setGalleryFiles([]);
    setGalleryPreviews([]);
    setExistingGallery([]);
    setDeletedGalleryIds([]);
  }

  function openCreateForm() {
    resetProductForm();
    setShowForm(true);
  }

  function closeForm() {
    if (saving) return;
    resetProductForm();
    setShowForm(false);
  }

  function handleChange(event) {
    const { name, value, type, checked } = event.target;

    setFormData((current) => {
      const nextForm = {
        ...current,
        [name]: type === "checkbox" ? checked : value,
      };

      const slugWasAutoGenerated = current.slug === createSlug(current.name);
      if (name === "name" && (!editingId || slugWasAutoGenerated)) {
        nextForm.slug = createSlug(value);
      }

      return nextForm;
    });
  }

  return {
    showForm,
    setShowForm,
    editingId,
    setEditingId,
    saving,
    setSaving,
    formData,
    setFormData,
    imageFile,
    setImageFile,
    imagePreview,
    setImagePreview,
    galleryFiles,
    setGalleryFiles,
    galleryPreviews,
    setGalleryPreviews,
    existingGallery,
    setExistingGallery,
    deletedGalleryIds,
    setDeletedGalleryIds,
    resetProductForm,
    openCreateForm,
    closeForm,
    handleChange,
  };
}
